#ifndef __MENU_TITLE_H
#define __MENU_TITLE_H

#define PSTR(a)  a

#define STR_MAINMENU	"< MAIN MENU >"
#define STR_SETTINGMENU	"< SETTING MENU >"

#define MENU1	"MENU1"
#define MENU2	"MENU2"
#define MENU3	"MENU3"
#define MENU4	"MENU4"
#define MENU5	"MENU5"
#define MENU6	"MENU6"
#define MENU7	"MENU7"
#define MENU8	"MENU8"


#define TOOL	"TOOL"
#define GAME	"GAME"
#define HOOD	"HOOD"
#define TICK	"TICK"
#define TV		"TV"

#define TXTS	"TXTS"
#define TIMES	"TIMES"
#define SOUNDS	"SOUNDS"
#define LIGHTS	"LIGHTS"

#define GAME1	"Game of Life"
#define GAME2	"FlyBrid"
#define GAME3	"GAME3"
#define GAME4	"GAME4"
#define GAME5	"GAME5"
#define GAME6	"GAME6"
#define GAME7	"GAME7"
#define GAME8	"GAME8"

#define EXIT	"EXIT"


#endif /* __MENU_TITLE_H */
